name: 'streamx-connector-github'
inputs:
  streamx-ingestion-url:
    description: 'StreamX ingestion API endpoint URL (e.g., https://ingestion.streamx.dev).'
    required: true
  streamx-ingestion-token:
    description: 'StreamX ingestion API authorisation token.'
    required: false
  action:
    description: 'Name of the GH action (e.g., sync, publish, unpublish).'
    required: true
  channel:
    description: 'Name of the StreamX ingestion channel.'
    required: true
  source-provider:
    description: 'Specifies the provider name used to determine the ingestion data source.'
    required: true
  workspace:
    description: 'Specifies the root directory for ingestion data lookup. Defaults to github.workspace.'
    required: false
  key:
    description: 'Defines ingestion message key value property. Required only with unpublish action.'
    required: false
  type:
    description: 'Specifies the sx:type metadata field within the ingestion message properties.'
    required: false
  include-patterns:
    description: 'Defines Ant-style path patterns for filtering ingestion data (e.g., styles/*.css, scripts/*.js).'
    required: false
  external-resource-url:
    description: 'URL property from where resource data is downloaded and used as ingestion data.'
    required: false
  debug-enabled:
    description: 'Configuration property to enable debug log level in GitHub Actions.'
    required: false
    default: 'false'
  snapshot-artifactory-token:
    description: 'StreamX artifactory token for SNAPSHOT usage only'
    required: false

runs:
  using: "composite"
  steps:

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        cache: 'maven'

    - name: Set up JBang
      uses: jbangdev/setup-jbang@main

    - name: Configure java
      run: |
        jbang jdk install 21 ${{env.JAVA_HOME_21_X64}}
      shell: bash

    - name: Run the action
      id: action
      run: |
        if [[ "${{ inputs.debug-enabled }}" == "true" ]]; then
          export JDK_JAVA_OPTIONS="-Dquarkus.profile=debug"
        fi
        jbang --java 21 --fresh --repos 'streamx-maven-public-releases=https://europe-west1-maven.pkg.dev/streamx-releases/streamx-maven-public-releases/' --repos 'mavencentral' dev.streamx:streamx-connector-github:1.0.0
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
