name: 'streamx-connector-github'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  action:
    description: 'Name of the action'
    required: true

runs:
  using: "composite"
  steps:
    - name: Inject streamx-connector-github repository credentials
      shell: bash
      run: |
        if [ -f ~/.m2/settings.xml ]; then
          if ! grep -q '<id>streamx-connector-github</id>' ~/.m2/settings.xml; then
            sed -i.bak 's@</servers>@<server><id>streamx-connector-github</id><username>${env.GITHUB_ACTOR}</username><password>${env.GITHUB_TOKEN}</password></server></servers>@' ~/.m2/settings.xml
          fi
        else
          mkdir -p ~/.m2/
          cat <<\EOF > ~/.m2/settings.xml
        <?xml version="1.0"?>
        <settings>
          <servers>
            <server>
              <id>streamx-connector-github</id>
              <username>${env.GITHUB_ACTOR}</username>
              <password>${env.GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
        fi

    - name: Set up JBang
      uses: jbangdev/setup-jbang@main

    - name: Run the action
      id: action
      run: jbang --java 21 --fresh --repos 'streamx-connector-github=https://maven.pkg.github.com/streamx-dev/streamx-connector-github/' --repos 'mavencentral' dev.streamx.githhub:streamx-connector-github:0.0.1-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
