name: 'streamx-connector-github'
inputs:
  streamx-ingestion-url:
    description: 'StreamX ingestion API endpoint URL (e.g., https://ingestion.streamx.dev).'
    required: true
  streamx-ingestion-token:
    description: 'StreamX ingestion API authorisation token.'
    required: false
  action:
    description: 'Name of the GH action (e.g., sync, publish, unpublish).'
    required: true
  channel:
    description: 'Name of the StreamX ingestion channel.'
    required: true
  source-provider:
    description: 'Specifies the provider name used to determine the ingestion data source.'
    required: true
  workspace:
    description: 'Specifies the root directory for ingestion data lookup. Defaults to github.workspace.'
    required: false
  key:
    description: 'Defines ingestion message key value property. Required only with unpublish action.'
    required: false
  type:
    description: 'Specifies the sx:type metadata field within the ingestion message properties.'
    required: false
  include-patterns:
    description: 'Defines Ant-style path patterns for filtering ingestion data (e.g., styles/*.css, scripts/*.js).'
    required: false
  external-resource-url:
    description: 'URL property from where resource data is downloaded and used as ingestion data.'
    required: false
  debug-enabled:
    description: 'Configuration property to enable debug log level in GitHub Actions.'
    required: false
    default: 'false'
  snapshot-artifactory-token:
    description: 'StreamX artifactory token for SNAPSHOT usage only'
    required: false

runs:
  using: "composite"
  steps:
    - name: Download streamx-connector-github snapshot dependency
      if: inputs.snapshot-artifactory-token != ''
      shell: bash
      run: |
        if [ -f ~/.m2/settings.xml ]; then
          if ! grep -q '<id>streamx-maven-snapshots</id>' ~/.m2/settings.xml; then
            sed -i.bak 's@</servers>@<server><id>streamx-maven-snapshots</id><username>oauth2accesstoken</username><password>${env.SNAPSHOT_ARTIFACTORY_TOKEN}</password></server></servers>@' ~/.m2/settings.xml
          fi
        else
          mkdir -p ~/.m2/
          cat <<\EOF > ~/.m2/settings.xml
        <?xml version="1.0"?>
        <settings>
          <servers>
            <server>
              <id>streamx-maven-snapshots</id>
              <username>oauth2accesstoken</username>
              <password>${env.SNAPSHOT_ARTIFACTORY_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
        fi

    - name: Set up JBang
      uses: jbangdev/setup-jbang@main

    - name: Run the action
      id: action
      run: |
        if [[ "${{ inputs.debug-enabled }}" == "true" ]]; then
          echo $'Inputs:\n${{ toJSON(inputs) }}'
          echo $'Event Inputs:\n${{ toJSON(github.event.inputs) }}'
          export JDK_JAVA_OPTIONS="-Dquarkus.profile=debug"
        fi
        jbang --java 21 --fresh --repos 'streamx-maven-public-releases=https:://europe-west1-maven.pkg.dev/streamx-releases/streamx-maven-public-releases/' --repos 'mavencentral' --repos 'streamx-maven-snapshots=https://europe-west1-maven.pkg.dev/streamx-releases/streamx-maven-snapshots/' dev.streamx:streamx-connector-github:1.0.1-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        SNAPSHOT_ARTIFACTORY_TOKEN: ${{ inputs.snapshot-artifactory-token }}
